* The 30th Anniversary of the Fall of the Soviet Union
- [[https://pca.st/n9h1c4q9][Link to source]]
- Moderated by Angela Stent (Nonresident Senior Fellow, Foreign Policy -- Center on the United States and Europe)
- Panelists
  - James Goldgeier -- Visiting Fellow, Foreign Policy -- Center on the United States and Europe
  - Fiona Hill -- Senior Fellow, Foreign Policy -- Center on the United States and Europe
  - Donald Jensen -- Director, Russia and Strategic Stability -- United States Institute of Peace
  - Vladislav Zubok -- Professor, Department of International History -- London School of Economics and Political Science
  - Pavel K. Baev -- Nonresident Senior Fellow, Foreign Policy -- Center on the United States and Europe

** Opening Statement by Angela Stent
- Panel commemorating the 30th anniversary of the collapse of the Soviet Union
- Current tensions between Ukraine and Russia remind us that the current contours of that collapse are not yet settled, at least not for Vladimir Putin
- 30 years ago, it was difficult to imagine how a nuclear armed superpower, the largest country in the world, could simply implode, rather than being defeated in a war
- Was easier for many to believe that the collapse had been instigated by the United States' intelligence services
- 30 years on, there are several important questions that we can look back on
  - Why and how did the USSR collapse
  - Was the collapse inevitable
  - How do we explain what came afterwards
  - How did things turn out so differently from what we hoped?

** Introductions
- Vladislav Zubok
  - Professor of history at the London School of Economics
  - Author of a new book: /Collapse: The Fall of the Soviet Union/
  - Will talk about whether the collapse was inevitable and how history might have turned out differently
- Donald Jensen
  - Director of Russia and Strategic Stability at the US Institute of Peace
  - Was a diplomat working at the US embassy in Moscow during the collapse of the Soviet Union and in the years that immediately followed
  - Will discuss how the US tried to understand what was going on in the Soviet Union during the collapse and what the US got right and wrong
- Fiona Hill
  - Senior Fellow at the Center on United States and Europe
  - Author of /There's Nothing Here For You/, book on the fall and resurrection of Russia
  - Will reflect on the meaning of the collapse and what came afterwards
- Pavel Baev
  - Nonresident Senior Fellow at the Center on United States and Europe
  - Will discuss the military implications of the collapse
- James Goldgeier
  - Visiting Fellow at the Center on United States and Europe
  - Coauthor of /Power and Purpose/ - discusses US/Russian relations in the '90s
  - Will discuss how the H.W. Bush and Clinton administrations dealt with the New Russia

** Panelist Statements
- Vladislav Zubok
  - 30 years ago, the accepted wisdom became that the death of the Soviet Union was inevitable
  - Yet, before the collapse few thought that the Soviet Union was doomed
  - This contradiction is the inspiration for Zubok's book
  - The evidence of this book challenges the inevitability narrative
  - Observers and historians of the Soviet collapse explain the collapse mainly by reference to long-term, structural factors and outside contingencies
    - Long-term structural factors
      - Bankrupt planned economy
      - Defunct Communist ideology
      - Cold War pressures
      - Anti-Russian nationalism in the borderlands
    - Short-term triggers and contingency factors
      - Reagan's Star Wars (SDI)
      - Soviet war in Afghanistan
      - Falling oil prices
      - Gorbachev's anti-alcohol campaign
      - Chernobyl disaster
      - Glasnost -- shook Soviet identity
  - Zubok's book argues that the above factors, important as they may have been, did not doom the Soviet Union
  - Challenges the idea of Mikhail Gorbachev as a visionary leader who ended the Cold War, let go of Eastern Europe and dismantled the Communist system
  - Gorbachev is at the center of Zubok's book but the focus is on his failures rather than his achievements
  - Book argues that Gorbachev's mistakes were the primary driver behind the quick demise of the Soviet Union
    - Ill designed economic reforms
      - Ruined the ruble
      - Left the center without funds
    - Rapid political liberalization
      - Triggered mutinies across the Soviet Union
      - The most fateful of these mutinies was "Rexit" -> /Russian/ nationalist separatism from the larger Soviet state
      - An under-studied aspect of the collapse is the role of Russian nationalism in imploding the center of the Soviet empire
      - A major driver of Russian nationalism was the Russian perception of Gorbachev as a failed leader
      - Inability to stop the descent of the country into economic misery and political chaos
  - As the reforms led to numerous simultaneous crises which engulfed the Soviet Union, Gorbachev proved to be an inept leader
  - Zubok argues that the role of Ukraine in the Soviet collapse has also been exaggerated by Western scholars
  - Argues that Ukrainian independence was a consequence, not a cause of the implosion at the center
  - Same applies to the role of the Poles
  - Poles were the first to realize that the political chaos at the heart of the Soviet Union offered them the political cover they needed to declare independence, and they took full advantage
  - USSR was killed by the implosion of the center, not by the pressures of the periphery
  - Gorbachev's failures created the environment for Putin's rise
  - The Soviet collapse led to a "time of troubles" and Putin restored the Russian state and rescued the Russian people from a condition of statelessness
  - The manner of Putin's rule shows that Putin's governing philosophy is a direct response to the causes of the failure of the Soviet Union
    - Maintains budget surpluses and large hard-currency reserves, unwilling to spend down reserves even in response to the pandemic -> does not want to be as bankrupt as Gorbachev was
    - Dedicated surpluses from high oil prices to the restoration of state power
      - Army
      - Police
  - However, Putin still struggles with some of the causes of Soviet collapse
    - The USSR broke up when its core, Russia, claimed sovereignty
    - The source of instability was the Russian majority, not rebellious national minorities
    - This majority can become a source of instability when, for economic or other historical reasons, it becomes disillusioned with the state and its leadership
- Donald Jensen
  - What was the collapse like from the point of view of the US embassy?
  - What did we miss? (A lot)
  - What did we misunderstand (Even more)
  - Start with what we misunderstood
    - Prior to 1990, in DC there was hardly any discussion of the possibility of the USSR collapsing
      - People assumed that the USSR would simply continue in one form or another
      - Jensen himself assumed that the USSR would go on, for at least another generation
      - We have not grappled sufficiently with the fact that so many people got this core question so wrong
    - Assumption that the forces challenging the USSR were largely democratic and free-market in nature
      - Yeltsin led a /coalition/ of forces in Soviet society, not all of which were healthy
      - By thinking that this was a coalition of like-minded democrats (like in Poland or the Balts) we fooled ourselves into thinking that the eventual outcome for Russia would be much the same
    - Much too much credit to Gorbachev's capacity for maneuver
      - Thought that Gorbachev's ability to outmaneuver the hard-liners meant that he could outmaneuver Yeltsin as well
      - Took a long time for people to realize that Yeltsin had the political advantage over Gorbachev
      - View of everyone as either a "hard-liner" or "reformer" was overly reductionist, and masked the actual splits within the Soviet political system
    - Misunderstood Yeltsin
      - Was initially seen as a threat to Gorbachev -> Gorbachev was a reformer, so anyone that opposed him must be a hard-liner
      - However, once Yeltsin gained the advantage and started the break-up of the Soviet Union, we viewed Yeltsin as a reformer and stopped talking about his many flaws
  - What did we miss completely?
    - Evidence that Yeltsin and the coup plotters had serious contacts between January and the date of the coup
      - Yeltsin himself, in June 1991 talked about a possible coup against Gorbachev
    - The entire centrality of money in the system
      - Party money
      - Origins of the oligarchs
      - Role of the KGB in creating a corporate state
    - The disillusionment of the 2nd and 3rd tiers of the /nomenklatura/
      - The lack of faith of mid- and lower-level party functionaries in the official ideology was, in retrospect, key to the collapse
      - These were the people who were brought to power by the coup
      - The corruption of this class of people was the reason reforms stalled
      - The fall of the Soviet Union was not a victory for democratic reformers, but rather was a victory for the rising generation of nomenklatura
  - We might be missing and misunderstanding things about Putin's Russia, which will leave us similarly surprised in the future
- Fiona Hill
  - Many of the myths we have in the United States re: the collapse of the Soviet Union, give the United States more agency than it deserves
  - The pressure from the West and NATO, in the end, wasn't that important
  - Furthermore, many of the internal pressures that outsiders thought were significant, turned out not to be
    - Baltic states
    - Environmental movement
    - Tensions in the Caucuses
  - Mistaken historical analogies with the fall of the Russian Empire during World War 1
  - However, unlike with the fall of the Russian Empire, the fall of the Soviet Union was instigated by an act of political rebellion in the core
    - /Not sure what Hill means by this/
    - /Wasn't the Russian Revolution also a rebellion in the core?/
    - /Maybe she means that it was a rebellion by the Russian ruling class?/
  - The fact that the collapse of the Soviet Union was largely instigated by members of the Communist Party itself serves as a cautionary tale for Vladimir Putin
  - Another underappreciated fact about the Soviet collapse is how much the collapse was driven by personal differences between Gorbachev and Yeltsin
  - Yeltsin had a different set of ambitions that were not compatible with Gorbachev's goals
  - Gorbachev's (perceived) mishandling of the economy also played an important role
  - Putin's agenda is as much about making Russia /solvent/ again as it is about making Russia great again
  - Another reflection of this is Putin's emphasis on centralized management of budgets and economic policy -- relinquishing economic power is seen as the first step to relinquishing political power
  - Outsiders never understood the true nature of the Soviet system
    - Focused a lot on Communism and central planning
    - Assumed that just removing central planning would lead to an overnight transformation
  - Assumed that privatization would lead to the creation of a bourgeoisie middle class, which would strengthen democracy, following patterns elsewhere (/i.e. East Asia/)
  - Didn't understand how intertwined the Russian economy was with the political system
  - For example, supply chains now spanned international boundaries
    - Factory in the Urals idled because it received raw materials from Uzbekistan and Azerbaijan
    - Kyrgyz herders having to cull all their livestock because they were cut off from the only market they served: Moscow
  - Western advisors never fully processed the complexity of this unraveling
- Pavel Baev
  - Wants to focus on the image of tanks in the streets of Moscow, during the coup in August
  - Was a very strong image
  - However, by the next morning, it became apparent that those commanding the tanks didn't know what they were doing, and so the coup plotters didn't stand a chance
  - But why? Why was the massive military of the Soviet Union not sufficient to hold the country together?
  - The accepted analytical wisdom of the time, after all, was that rather than /having/ a military machine, the Soviet Union /was/ a military machine
  - Moreover, the military was /designed/ to hold the country together under the sorts of pressures that emerged during 1991
  - The Soviet military had received a sequence of very heavy body blows in the years before the collapse
    - INF treaty - was signed by Gorbachev over the objections of the military brass
    - Withdrawal from Afghanistan - painful defeat, which discredited the military in the eyes of the Russian citizenry
    - Pressure of the breakdown of the Berlin Wall and the collapse of the Warsaw Pact, which entailed the withdrawal of hundreds of thousands of troops from Western Europe
    - Gulf War - demonstrated to the Russian military exactly how far behind it was when it came to modern warfare
  - These failures culminated in the pathetic performance of the Soviet military during the coup itself
  - This demonstrates that, contra received analytical wisdom, the Soviet Union was much more than a military machine
  - The analysis of the Soviet Union as a military-state missed all the non-military factors that led to the collapse
  - This was equally a problem with the Soviet leadership, which disdained soft sciences like sociology, which might have uncovered strains within society that presaged collapse
    - /I think this gives sociology far too much credit/
  - A key factor was a new generation of Soviet citizens who actively disdained the military
  - Another factor in the disillusionment of the military is the lack of effectiveness of the Soviet military in suppressing the rising ethno-political conflicts in places like Vilnius and Baku
  - The military was further undermined by economic developments outside the military
  - The fact that the military was intertwined with the Party meant that internal party-political intrigues paralyzed the military's leadership
  - These factors came together to nullify the Soviet military's great size and paper-strength
  - The important take-away from these factors is that it's easy to overstate the strength of the Russian military
  - The Russian military of today is far smaller than it was when the Soviet Union fell
  - Vladimir Putin has a hundred thousand troops on the border of Ukraine, and as bad as that it is, we must remember that the Soviet Union had a half a million troops in East Germany alone at the end of the Cold War
  - Russia is no longer a military-dominated state like it was during the Cold War -- reduced capacity for mobilization
  - /I have a different take: which is that the Russian military of today might actually be stronger than the demoralized, technologically backwards, incompetently led Soviet military of the past/
  - /I agree with Pavel that size is not a great indicator of strength, but that can cut both ways: a smaller military might actually be more easy to keep strong than a large one/
  - /Russian capacity for mobilization may have declined with the end of the Cold War, but the capacity of Western Europe to mobilized has arguably fallen even farther/
  - Audience question: to what extent was the defeat in the Soviet-Afghan war responsible for the collapse in confidence in the Soviet regime?
    - The defeat itself was less important than the overall senselessness of the war
    - The Soviet withdrawal from Afghanistan was fairly dignified -- nothing like the American withdrawal
    - The Red Army was able to regroup and refocus on what it saw as its main purpose, conventional war in Western Europe, after its retreat from Afghanistan
- James Goldgeier
  - When George H.W. Bush went to Germany in 1989 to lay out a vision of "Europe, whole and free" he included Russia as part of that vision
  - However, the US and Russia had far different ideas of what that vision meant
  - The US vision was one in which the US dominated European security
    - This is why the US maintained NATO even after the dissolution of the Soviet Union
    - This is why the US supported NATO's enlargement
    - Russia could join this US dominated European order as a junior partner
  - Russia, however, saw its role in Europe as being equal to, not subordinate to, the United States
  - One of the lessons of the past 30 years is that the US cannot and should not run European security
  - Needs to be a greater balance between the United States and European countries
  - Need to find a way to fit Russia into a European security architecture
  - This doesn't mean we need to be sanguine about Russian threats to European security
  - We need to talk as much about what assurances Russia can give Europe as what Europe can give Russia
  - On April 1, 1993 Bill Clinton gave a speech before he met Boris Yeltsin in Vancouver, where he talked about three transitions that were taking place in post-Soviet Russia
    - Transition from authoritarian state to democracy
    - Transition from a command economy to a market economy
    - Transition from an empire to a modern nation-state
  - The importance of the first two is widely discussed, but it's worth focusing on the latter
  - There was an idea in the '90s that if Russia could let go of its imperial claims it could exist in the world as a "normal" nation-state
  - However, we underestimate how much support for the independence of Ukraine and other post-Soviet nations was tied to internal jockeying between Yeltsin and Gorbachev; Yeltsin voiced support for national independence movement as a tactic to undermine Gorbachev, not because he genuinely wanted to break up the Soviet empire
  - As early as 1997, Yeltsin was already approaching Bill Clinton for assurances that Ukraine would be kept out of NATO
  - Goldgeier has been teaching a graduate level course on the relationship between the United States and Russia since 1991, and notes that the semester begins with a Russian president asking his American counterpart for help building a market democracy and ends with an American president asking his Russian counterpart to help build corrupt authoritarianism
  - It's important to remember, after 30 years, that at the time of Russian independence from the Soviet Union, there were genuine hopes among even the Russian leadership that Russia would become a market democracy integrated into the West
    - /Really? Everything I've read indicates kind of the opposite, including many of the viewpoints of other people on this panel/

** Panel Discussion
- In the '90s and to some extent in the 2000s, we had an awful lot of political science theories about transitions; many of those theories have been discredited today when countries either failed to make "inevitable" transitions or reversed "irreversible" transitions. Why were we wrong in our belief that Russia would want to become more integrated with the West?
  - Vladislav Zubok
    - It's instructive to look at the papers for the Democratic Russia movement of the '90s
    - 30 years later, those papers have an air of unreality about them
    - With hindsight we can see that those people had the same approach as the Bolsheviks in 1917
    - The more the old order was eradicated, the easier it would be to turn Russia, and its people into the ideal that they held, namely to be like Americans
    - They were speaking unironically of turning Russia into a "new California" over the next 20 years
      - /Instead of turning Russia into California, we turned California into Russia/
    - Had no idea of the difficulty of turning a deeply traumatized, broken nation like Russia into a functional market democracy
    - Democratic Russia was particularly hostile to the Russian state -- saw the state solely as an obstacle that had to be destroyed before the right type of state could be rebuilt -- the parallels to 1917 should be obvious
    - Lots of hostility among Russian Democrats towards the military solely because the military was an instrument of the old regime; just like hostility that the Bolsheviks had towards tsarist officers
    - Zubok disagrees with Pavel's implicit assumption that the role of the Russian military was to protect the state from all threats
    - The Russian military had the politics bred out of it -- was trained to stay out of internal political discussions
    - Thus when internal political discussions threatened to break up the Soviet state, the military leadership was unable to take a stand to preserve the state
    - /I agree with the fact that the Red Army was not trained to preserve the state against threats from within, but I think it leaves open the question of why the KGB was unable to preserve the Soviet Union/
    - The lesson that the Russian Democrats forgot was that you need a state, however imperfect, in order to achieve your goals
    - /To be fair, this is an easy lesson to forget, going by the fact that the US also forgot it in Iraq/
  - Donald Jensen
    - This was the era of Frank Fukuyama -- "history had ended"
    - Culture and ideology no longer mattered, democratic transitions were seen as deterministic
    - Many Western observers were totally unfamiliar with Russian history or culture
    - We didn't understand how much of a trauma the break-up of the Soviet Union was to Russian society
    - Had we understood, we could have perhaps worked harder to mitigate that trauma
    - By 1993 we were already facing a dilemma between supporting Yeltsin or pushing for further economic reforms
    - We chose to support Yeltsin and thus started a long slide into authoritarianism that culminated with Putin
    - Our shambolic handling of economic reform in reform stands in stark contrast to our handling of the security challenges posed by ex-Soviet nuclear weapons
  - Fiona Hill
    - We assumed that the destruction of the Communist Party was sufficient -- it was inevitable that Communism would be replaced by democracy as soon as it was removed
    - Just like tsarist officers and administrators fled Russia after the Bolsheviks took over, many Communist administrators and officials emigrated from Russia once the Soviet Union fell, similarly depriving the new Russian state of administrative capacity
    - Didn't appreciate the level of economic disruption to people's everyday lives caused by the destruction of the state -- goes back to earlier example of Kyrgyzstan sending meat to Moscow -- the sudden independence of Kyrgyzstan meant meat shortages in Moscow even as livestock was being destroyed in Kyrgyzstan for lack of a market
    - /And of course, we have similar stories during the Bolshevik revolution of farmers burning crops and spilling milk into rivers even as urban areas were starving/
    - In addition to having no idea how to stand up an economic system, western advisors didn't know how to stand up a political system
    - Russia had no history of independent political parties, save for a brief period for a couple of years between the fall of the tsar and the takeover of the Bolsheviks
    - The "Strengthening Democratic Institutions" program at the Kennedy Center, where Fiona worked during the early '90s had a program to bring over Russian political party leaders
    - Toured the US, examining how US politics and political institutions worked
    - The lesson that the Russian politicians took away was not an appreciation for democratic institutions, but an appreciation for the manipulation of democratic institutions
      - Political action committees
      - How to "manufacture" a candidate
      - How to manipulate institutions like the electoral college
    - We didn't appreciate how little trust there was in the Russian political system
    - We showed them how to build a party from the top down, with elites using Western tools of advertising and manipulation to move the masses
    - Putin's idea of a "managed democracy" doesn't originate with Putin, it originates in the US
    - /In which the mask slips and our think-tank masters reveal themselves to have been neoreactionaries all along/
    - Movie recommendation: /Spinning Boris/ - documentary about how American political consultants helped Boris Yeltsin win an election that he seemed sure to lose
  - Pavel Baev
    - Injustice and inequality
    - The impact of sudden inequality is hard to overstate
      - Large numbers of Russians saw themselves sinking into poverty
      - Meanwhile a tiny fraction got very very rich, and did so in a manner that was impossible to ignore
    - This inequality led to injustice
      - Feeling that the Russian people were being treated poorly by their new masters
      - Feeling that Russia itself was being treated in an unjust manner by the West
    - These problems are not just a problem for states transitioning from authoritarian regimes to democratic ones, they're problems for authoritarian regimes as well
    - Injustice and inequality were key drivers of the protests in Belarus in the summer of 2020
    - The difference is that authoritarian regimes have a much wider set of tools to deal with mass movements than democratic ones
    - One of the root causes for Putin's recent aggression in foreign policy might be the fact that he's having to deal with increased discontent over economic stagnation and inequality at home
  - James Goldgeier
    - In September 1990, Goldgeier was in Russia, touring the country with a Russian parliamentarian
    - Holding a series of town halls to elicit popular opinions on the Russian constitution
    - All of these town hall meetings had the same dynamic
      - The parliamentarian goes up and talks about democracy and how the constitution should be structured
      - Audience questions would all be about basic economic and quality-of-life issues -- what good is a constitution when there is no bread in the supermarkets?
    - Democratic ideals count for little when governments are delivering for their people
    - We can argue that Putin got lucky in that he came to power during a period of high oil prices that enabled him to deliver great economic improvements for ordinary Russians at little visible cost to them
    - However this doesn't reduce the point that governments have to deliver security and economic stability, and there wasn't enough attention paid to this during the post-Soviet transition
- Do you think that the Russian government will ever publicly come to terms with the legacy of the Soviet Union in the same way that the German government came to terms with the legacy of Nazism?
  - Vladislav Zubok
    - There were efforts during the '90s where relatives of those who perished in the Great Terror, along with democratic reformers, attempted to repudiate the past
    - But the past is a resilient thing
    - This was not an overnight process for Germany and Germany undertook the effort to grapple with its Nazi history under almost ideal geopolitical conditions
      - NATO membership
      - EEC membership
      - American nuclear umbrella
    - Even with these ideal conditions, it took Germany decades
    - Much more difficult process for Russians
    - Russians don't have this luxury
    - The current Russian state is seen as a restoration of order and state power after almost a decade of statelessness
    - Geopolitical situation is much different, at least from the point of view of the Russian government
      - Confronted by a hostile Europe on one side, led by the United States
      - Unfriendly Turkey to the south
      - China to the East -- is a partner, but is also a rival
    - Russians don't have the luxury of being able to confront their past
    - As long as this geopolitical uncertainty lasts, Stalin will remain popular
      - Relates a joke: when asked, "What do you think about Stalin," people will take a long pause and reply, "... But he won the war"
    - As long as Russia remains outside of and opposed to a common European security architecture, it will be unwilling to confront its past
  - How would you relate the events that we've been talking about (the fall of the Soviet Union) to the current situation between Russian and Ukraine
    - Fiona Hill
      - 30 years ago, when Ukraine broke away, it might have been a gain for Yeltsin, but for most Russians, it was a huge loss
      - Putin laments the loss of statehood and empire -- critiques the Bolsheviks for breaking up the tsarist Russian Empire, even as he engages in Soviet nostalgia
      - Putin frames himself as the restorer of the Russian state and the Russian empire
      - The official mythology of the Russian state goes back to pre-revolutionary times, focusing on the rise of the Russian empire, from Muscovy and Kiev
      - Ukraine, of course, is an integral part of this past
      - Putin doesn't view Ukraine as a real country -- famously told George W. Bush at Bucharest in 2008, "You know, George, Ukraine isn't really a country"
        - Sees Ukraine as a collection of leftovers from the Russian, German and Austro-Hungarian empires
      - Frames his seizure of Crimea as a restoration of the lands of the historical Russian empire, hearkening back to Catherine the Great
      - The real irony is that Putin should be thankful for the collapse of the Soviet Union -- the only reason he's President of Russia is because the Soviet Union collapsed
      - Putin is thinking about how he can remain in office, like Lukashenko in Belarus
      - Putin's actions against Ukraine are as much about him attempting to secure his own position as they are about him trying to secure Russia's position
      - There is no external threat to Russia
      - The only real threat that Vladimir Putin faces is internal
      - What Putin fears the most is going down in the same way that Gorbachev went down
      - /This is why I think it'll be impossible to deter Russia from military action against Ukraine -- the military action is being driven by domestic political dynamics, and is not a response to external pressures/
  - What is Putin's ultimate aim? Is he trying to restore the Soviet or tsarist Empires?
    - Donald Jensen
      - Putin is trying to restore Russia's greatness
      - Putin wants Russia to be regarded as a great power by the West
      - As long as Russia's great power ambitions bring it into conflict with its neighbors, Russia will continue to pose a challenge, regardless of whether it faces any military threats or not
    - Pavel Baev
      - The urgency of the crisis in Ukraine comes from Russia's drive to be seen as a great power
      - In Vladimir Putin's view, if Ukraine goes its own way, then Russia is not a great power
      - However, the seizure of Crimea and the attacks on the Donbas region accelerated Ukraine's shift in allegiance towards the West
      - Putin cannot admit this
      - Thus the current build-up is not just a gesture by Putin to get attention from Europe and the United States, it has a deeper and more dangerous reason
