#+TITLE: Contra Moldbug on Sovereignty

/A response to [[https://graymirror.substack.com/p/a-brief-explanation-of-the-cathedral][Moldbug's latest essay]]/

#+begin_quote
This form of government—the form that doesn’t leak power—has a name. It is called a monarchy. The form of government currently used by Mutopia also has a name. It is a bureaucracy, which is one kind of oligarchy. (“Deep State,” if you absolutely must.)
#+end_quote

Since when are monarchies immune from leaking power? This is why Moldbug annoys me so much. He constantly goes on about how historically knowledgeable he is... and then makes basic errors, like this. Monarchies leak power into their bureaucracies /all the time/. The stereotype of the "good Tsar" and the "evil Minister" exists for a reason. The normal case with monarchy is that the monarch delegates almost all of his or her power to bureaucrats, and the overall effect is much the same as that of a normal bureaucracy. The bureaucrats then go out to universities, etc, etc, to find ways of implementing their policies, and then process of sovereignty leaking proceeds as normal.

In fact, it's so normal that when a monarch attempts to reverse this process, it often leads to revolution. Both the Magna Carta and the Glorious Revolution were responses by British nobility to a monarch that was seen as being overly centralizing. Similarly, in Russia, one of the root causes of the Bolshevik Revolution was that Tsars Alexander III and Nicholas II styled themselves as old-school divine-right monarchs (instead of the more modern parliamentary monarch), and, as a result, attempted to roll back and slow down some of the sovereignty diluting changes of their reformist predecessors, most notably Tsar Alexander II. 

In my view, /every government leaks sovereignty/. Eventually, all the sovereignty of a government leaks out, and it falls. Either it is toppled by revolution from within or invasion from without. Sometimes it's both, as with the Roman Empire, where internal instability weakened the Empire and made it easier for outsiders to invade. Then the new regime starts with a new stock of sovereignty, which starts the process all over again.

Moreover, this process isn't just limited to governments. Corporations undergo a similar process as well. The small startup, with the charismatic CEO grows into the multibillion dollar behemoth. Eventually the CEO leaves, or is forced out. A new CEO steps in, but he or she doesn't have the personal authority of their predecessor. Decisions that, at one point, were handled by executive fiat, now have process around them. Different departments see themselves as having their own interests, rather than being subordinate to the interests of the firm as a whole. Eventually, the corporation, while still profitable, becomes vulnerable to disruption by the next bright young startup, as its decision-making is more sensitive to whether the right process was followed than to whether the right decision was made. We're seeing this right now Intel and TSMC, but examples of this pattern litter the corporate landscape.

In theory the successor CEO, monarch, or president can retain the brilliant, personalized decision-making of their predecessor. In practice, though, this rarely happens. If appointed from without, the successor doesn't have the same level of personal loyalty from the bureaucracy that their predecessor had. If promoted from within, the successor is a person who came to their position by following the rules that the original CEO set forth. They are likely to be exceedingly deferential to those rules, seeing as how they were responsible for both the success of the organization as a whole, and their personal success in particular.

It is the rare President, monarch, or CEO who can reverse this process, and the actual reversal more often resembles yet another revolution than a gradual change in the way the organization functions. The most brutal example of this is Mao Zedong's Cultural Revolution, which was more directed at the bureaucracy of the Communist Party itself than it was at the peasantry it governed. Another similar example is Stalin's repeated purges of the Soviet Politburo, and his repudiation of Lenin's NEP. Somewhat (but only somewhat) less brutally, Abraham Lincoln forced through fundamental reforms in the United States' economy by forcing the South to go cold-turkey on the slave labor to which it had become accustomed.

A less brutal example from corporate America is Steve Jobs' revitalization of Apple, which involved the cancellation of many projects and the unilateral ending of Apple's many licensing deals with third-party hardware vendors. Another such example is Satya Nadella's turnaround of Microsoft, which resulted in something like 30,000 layoffs, the shuttering of Microsoft's mobile devices division, the ending of Windows Phone, and wholesale adoption of "Agile" software development methodologies all across the organization. 

Leaking sovereignty is a fundamental property of bureaucracy, but the problem is that in order to run a moderately large organization, much less an entire country, one needs bureaucracy. There's simply too much going on for a single person or group to be directly responsible for everything, and one needs relatively simple, repeatable process in order to ensure that basic services are provided in an understandable and repeatable fashion. In my view, the only way to fix sovereignty leaks is with the occasional reboot, and, as a result, we should try to make the reboot process as painless as possible. Monarchies, unfortunately, are /incredibly difficult/ to reboot. They don't give way gracefully; they need to be put down with fire and blood.
