* The Wizarding World Is Not A Libertarian Paradise
In the Salt Lake Tribune, [[https://web.archive.org/web/20220226134616/https://www.sltrib.com/opinion/commentary/2022/02/26/henry-rymer-harry-potters/0][argues]] that the wizarding world of Harry Potter is actually an argument for libertarianism. Despite left-liberals' use of Harry Potter tropes as a "literary cudgel" against their opponents, he points out that the world of Harry Potter is a world in which most people are armed, and one of the core messages of the books is a healthy skepticism towards government bureaucracy, as evidenced by Hogwarts' inability to protect its students from danger and how the fifth book is focused on governmental failures.

Initially, my response to this was the same as my response to left-liberals using Harry Potter as an argument. Harry Potter isn't real. He's [[https://www.readthesequences.com/The-Logical-Fallacy-Of-Generalization-From-Fictional-Evidence][generalizing from fictional evidence]] . But the more I thought about the argument, the more I realized I didn't even have to go that far. Neither the setting nor the subtext of Harry Potter is libertarian in nature.

Yes, wizarding world is one where most every adult has a wand. Yes, with intent and focus, these wands can be used to kill, giving them a certain surface similarity to firearms. But did Rymers miss the part in book 1 where every wand is registered? When Harry gets his wand from Ollivander, Ollivander is able to consult his registry and determine that the core of his wand came from the same source as Voldemort's wand. Along the way, he also discusses the details of the wands issued to Harry's parents. The implication is clear: every wand in the wizarding world is both tied to a single individual and registered with the manufacturer who created it. The wizarding world, in that sense, is more akin to the Democrats' goal for gun control, where guns are available, but only from licensed manufacturers, are not transferable, and whose serial numbers are recorded in a registry accessible to the government. It is not a world where I can make my own wand from an 80% wand kit. It is not a world where I can 3D print my own wand. Everyone seems to be okay with this. I don't see anyone discussing the dangers of the wand registry. There are no arguments about how the fact that every is registered gives the government the ability to take away wands from whomever it pleases.

Second, in the world of Harry Potter, you don't get to just use a wand once it's been issued. Students of Hogwarts are repeatedly admonished that the use of magic outside the school is strictly forbidden until graduation. Students are issued their wands when they're inducted into Hogwarts at the age of 11. They graduate at the age of 18. Is it really a libertarian argument to claim that only graduates of a seven year training course ought to be allowed firearms? In that sense, students at Hogwarts receive more wand training than our soldiers receive with their firearms. Note that graduation from this training course is not guaranteed. Hagrid, most notably, was expelled from Hogwarts, and as one of the conditions of his expulsion, his wand was snapped in half, forever limiting his ability to use magic. Moreover, even when Hagrid's name is cleared, the Ministry of Magic doesn't seem to take any steps to restore his wand to him. And, once again, everyone is okay with this fact. Hagrid's rights were taken away through a miscarriage of justice. They are never restored, even after the state acknowledged its error. Is this libertarianism?

The wizarding world is one where rights to privacy and against self-incrimination are trampled to a shocking degree. They examine people's memories at trial! If any such magic or technology existed in our world, it would face a barrage of Fourth and Fifth Amendment challenges. If searching through people's papers and possession is illegal, then so should rifling through the contents of their mind. If individuals have a right to keep silent rather than incriminate themselves, being able to bypass that with direct memory examination is a clear subversion. Furthermore, the use of magical wards that can detect spells indicates that the wizarding world is heavily surveilled, even by our standards. When Harry uses his wand outside of Hogwarts, that usage is instantly recorded, and he is reprimanded, even though there was no human wizard present to witness him doing so. This kind of pervasive surveillance is taken as a given, and doesn't elicit any comment, even from those who are otherwise skeptical of the government.

Finally, Rymers argues that one of the underlying messages of Harry Potter is skepticism towards the state. But is that really true? While many wizards accept that the Ministry of Magic has failed in certain particular ways, I don't see any wizard making the next logical step and claiming that the powers granted to the Ministry of Magic are overbroad and should be pared back. Indeed, the aspiration of most of the students at Hogwarts is to get a job at the Ministry of Magic. Instead the explanations for the Ministry's failures all boil down to claiming that the wrong people are in charge, and if only the right people were in place, the failures would be resolved. That isn't a libertarian argument. That's the same argument used by apologists for Communism when libertarians point out the failures of the Soviet Union and Maoist China.

This reply to Rymers is admittedly a bit silly. But I don't think it's any sillier than the original argument. Rymers claims that Harry Potter has a libertarian subtext. I think this claim is based on a very surface level understanding of Harry Potter, and a closer reading of the text yields an argument closer to the traditional left-liberal interpretation. The wizarding world is statist and disrespectful of individual rights, and taking our world closer to it is taking our world further away from the ideals of libertarianism.
