* Operation Z: The Death Throes of an Imperial Delusion

RUSI has published a decent analysis of the war thus far, along with speculation of how the war might unfold in the second phase. Despite the grandiose title, "[[https://static.rusi.org/special-report-202204-operation-z-web.pdf][Operation Z: The Death Throes of an Imperial Delusion]]", I found it useful summary of the war thus far. The authors, Jack Watling and Nick Reynolds, interviewed Ukrainian officers and conducted their own fieldwork to sum up how things went wrong for Russia in the opening stages of the war, how Russia has refocused towards more limited objectives, and what this means for the Russian economy and western diplomatic and political strategy as the war drags on. My summary and analysis follows.

The opening phases of the war are familiar to most, but this report does bring to light some facts that were not well publicized during the chaos of late February. One is that, at least in the first 72 hours or so, Russian electronic warfare does appear to have been quite effective. Ukrainian radar operators reported heavy jamming, along with extensive use of decoys posing as Russian aircraft. Then as Russian troops advanced, this electronic warfare slackened. The authors surmise that Russian commanders were unwilling to risk rare and expensive electronic warfare assets too close to the front lines, and thus they had to cease jamming lest their jamming disrupt their own communications. 

Another interesting tidbit is the confirmation that the Ukrainians had advance warning of the Russian attack on Hostomel airfield. Ukrainian intelligence had picked up discussions between VDV commanders about an attack on the Antonov airfield, and were able to preposition forces to counterattack before the airborne infantry had arrived. There is reporting that this information was forwarded to the Ukrainians from Western sources, but the report does not speculate on the methods by which the Ukrainians determined that Hostomel airport was a likely target early in the conflict.

Ukrainian soldiers also reinforce an underemphasized point in the coverage of the war: the importance of artillery. As a Ukrainian general notes: "anti-tank weapons slowed them [the Russians] down, but what killed them was our artillery." Although Javelins and Bayraktars are getting a lot of press, the most important weapon, from the Ukrainian perspective, is the simple towed or self-propelled howitzer. Massed artillery fires, coordinated by drones, or even civilians reporting Russian movements with their smartphones, was decisive in countering the Russian assault on Kyiv.

However, despite their many early successes, the Ukrainians interviewed for the report readily admit that the early fight was not as much in their favor as the media made it out to be. In order to reinforce Kyiv, which the Ukrainians judged to be a key political objective for the Russian troops, they had to strip units from the east of the country. They did so with the full knowledge that doing so would compromise their defensive efforts in the south. As we've seen, the area of greatest Russian success has been in the south of Ukraine, especially along the vast swath of territory between Kherson and Mariupol, almost all of which is now in Russian hands. 

Furthermore, the fighting in northeastern Ukraine extracted a very heavy toll on the defenders. There, unlike around Kyiv and in the east of the country, the defense was primarily carried out by territorial defense units leavened with special forces. These units suffered very heavy casualties as, at times, the Ukrainians had to rely on sheer numbers in order to stop the Russian onslaught. This has depleted many of these special operations squads, potentially limiting Ukraine's ability to mount harassment attacks or disruptions of Russian supply lines in the future.

Nevertheless, by late March, it had become clear to the Russians that their initial aims of toppling the government in Kyiv establishing their own government in its place were unlikely to come to fruition, and the Russians revised their war aims. The report argues that this revision reflects the outcome of a power struggle within the Russian government between the FSB and Ministry of Defense. It seems that the initial invasion was planned by the FSB. However, as the assumptions underlying the initial invasion plan proved to be hopeless optimistic, the Ministry of Defense has now seized control and is refocusing the Russian effort towards what it perceives to be more achievable objectives. 

While the Russian military may have refocused its sights on the more limited goal of capturing the Donbas, the next few weeks are unlikely to produce a decisive outcome that will end the war one way or the other. While the Russian military has been weakened, it is far from defeated, and is still capable of fighting and making gains despite the debacle that was the initial two months of this war. Meanwhile, the Ukrainians have withstood the initial Russian attack without losing their capital, but are facing a slowly deteriorating situation in the south and east. Both countries are girding themselves for a protracted battle. However, the authors argue that time favors the Ukrainians. Ukraine has mobilized its society for total war in a way that Russia has not. Combined with the increasing levels of Western armaments flowing into Ukraine, this means that the Ukrainian military will grow stronger over time, and will be better able to mount counterattacks to threaten the supply lines for the Russian advances around Izyum and Donetsk.

Another reason the trend lines favor Ukraine is the impact of Western sanctions on Russian military production. The authors looked at the wreckage of a 9M727 cruise missile, one of the many munitions launched by the Iskander system. They found that, of the seven ports with which the missile's flight computer receives data and sends commands, six are manufactured in the US. Furthermore, the circuit board housing the computer itself, and the rails which isolate the board from the vibration and acceleration that the missile undergoes, are also of US make. 

The 9M727 is not an exception. The Russian "Tornado" MLRS uses gyroscopes sourced from the US. Russian Tor anti-aircraft systems rely on British-manufactured radio oscillators. Russian military radios are dependent on components from the Netherlands, Germany, South Korea and Japan, all of whom have imposed sanctions and export controls on components going to Russia.

Given this vulnerability in its military-industrial complex, why did Russia choose to go to war in Ukraine? The authors argue that Russia expected the war to be short and the West to be disunited. They were counting on European dependence on Russian energy supplies to reduce European willingness to impose strict economic sanctions. That, combined with an expectation of quick Ukrainian collapse meant that any potential disruption to critical supplies for manufacturing weapons was expected to be brief and manageable.

The length of the war and the unity of the Western response has shattered this assumption. The Russian government has convened an interdepartmental committee on weapons production, to coordinate resource sharing among producers. They've embarked upon a crash import substitution program, importing substitutes for western components from friendly countries. The FSB has also sought to import components via covert channels, laundering dual-use components through neutral third parties or even engaging in outright smuggling. Finally, Russia is recreating the industrial espionage programs it had during the Cold War, in order to acquire the ability to manufacture western components at home.

Will these measure be effective? Perhaps. The most effective means for Russia to acquire Western components is likely to be via neutral third parties, such as India and China. These countries have extensive economic ties with the West, as well as diplomatic importance beyond the current conflict. Thus the United States and EU may not be willing to impose harsh economic sanctions to limit the flow of dual-use components into these countries. I don't think Russia will be very successful with import substitution. Many of the components that Russia relies on for its weapons manufacture, such as computer chips, are themselves the product of long supply chains. Countries with far higher GDP and technical skill, such as the United States and China, have found it very difficult to reach autarky for electronic components. I don't find it likely that Russia, even given a decade or more, would be able to reach a position of self-sufficiency with regards to the integrated circuits that it requires for its precision guided munitions.

After covering the military situation, the authors change focus towards the political situation inside Russia. They note, along with many others, the strange fact of the war having been launched very little preparation or justification presented to the Russian public. When Russia launched its operation to take Crimea and support the formation of the Donetsk and Luhansk People's Republics, there was months of preparation. By comparison, this war, despite involving an order of magnitude more soldiers and occurring on a far grander scale, received approximately ten days of preparatory coverage, and just two speeches by Vladimir Putin. This is, according to the authors, the clearest indication that the Russian government expected a quick victory. They were expecting to present a toppled Ukrainian government as a /fait accompli/, not just to the West, but to their own people as well.

But the Ukrainians did not cooperate with the Russian master plan. This meant that, for a short while, there was a window where genuine dissent against the war could be expressed. There were street protests in Moscow and St. Petersburg against the war. The Ukrainian government did its best to take advantage of this period of openness, using both official channels on social media and person-to-person connections to try to spread the truth about Russian military failures among the Russian people.

This window soon slammed shut. The Russian government blocked Western social media and imposed penalties of up to 15 years in jail for spreading "disinformation". While motivated users can still seek out foreign sources of information by e.g. using VPNs, the lack of open access combined with the penalties for reposting Western coverage of the war has meant that knowledge of the true state of the war has remained limited. Only those willing to risk the displeasure of the government, and their trusted friends and family are informed about the true state of the conflict.

Having secured the domestic information environment, the Russian government chose to escalate its rhetoric. Ukraine is now being portrayed as the battlefield in a greater struggle between Russian and Western societies and systems of government. While the Russian government itself is still referring to the conflict as a "special military operation", it is no longer censoring those outlets which refer to it as a war. The authors argue that this is a sign that the Russian government will formally escalate the conflict on May 9, Victory Day, which was initially speculated to be considered as an end date for the war.

However, I'm not so sure I agree with that conclusion. While strident rhetoric can presage escalation, it can also be a way for a government to recast defeat as victory. I recall how, after the Gulf War, Saddam Hussein cast the "mother of all battles" as a victory for the Iraqi army, arguing that, although it suffered extremely heavy losses, the fact that it "prevented" Coalition forces from entering Iraqi territory meant that the conflict was actually an Iraqi victory. While it's unlikely that Putin is doing the same thing here, I think it's /possible/ that Putin is preparing to recast the defeat of the Russian army in Ukraine as the successful prevention of a NATO invasion.

Finally the authors look at potential avenues of political escalation outside of Ukraine. They argue that Moldova, in particular, is at risk. Russia has a brigade of troops in the breakaway province of Transnistria, and there is evidence that Russian agents are sponsoring protests against the Moldovan government's measures to ban pro-Russia symbols, such as the Cross of St. George. The plan, according to the report, is to build these protests towards a crescendo on May 9. The expected suppression of these protests can then be used by the Russian government as propaganda indicating that the West is suppressing the commemoration of the victory over Nazism.

I think this is the weakest part of the report. While there has been some unrest, including a rocket attack on a government building in Transnistria that may have been a false flag, I haven't seen very much news at all about protests against the Moldovan government. Protests, to the extent that they have occurred, have been small scale and have not resulted in the sort of violent reaction that would make for good propaganda. I find it unlikely that the Russian government will choose to escalate the war beyond Ukraine before the current campaign for the Donetsk and Luhansk oblasts has either been successfully concluded or has been repelled by the Ukrainians. While Russia does have troops in Moldova, those troops are isolated from resupply and all indications have been that their role is to threaten an attack into Ukraine, forcing the Ukrainians to keep some units back in order to cover off that eventuality. I think Russia has neither the means nor the motivation to pursue a significant escalation at the present moment.

So there we have it. A little over two months into the war, the Ukrainians stand firm, having repelled the initial Russian assaults on Kyiv and Kharkiv. While the Russians continue to make progress in the Donbas region, all indications is that advances are slow, and the Russian army is paying a steep price for every village it takes. Nevertheless, victory is not inevitable for Ukraine. Russia has a made a deliberate decision to escalate its rhetoric, and there is a real possibility that it will call for a general mobilization on May 9. Russia may well renew its offensive in the summer. To ensure that Ukraine can successfully continue to resist Russian aggression, the West needs to continue to provide Ukraine with the supplies that it needs in order to successfully stop and reverse Russian advances. Furthermore, western governments should increase their diplomatic engagement with neutral governments to prevent the flow of dual-use components reaching Russian users. Finally, Western governments need to coordinate among themselves to ensure that they stand firm in the face of potential economic damage caused by Russian restrictions of energy supplies. Victory over Russia today looks far more likely than it did in February, but there still a long hard road ahead.
